### ISSUE TITLE
ChunkMetadataAnchorSource escalates HEAD to GET on 404/429, doubling load on a refusing peer

### ISSUE THREAD

**Issue by vilenarios** [ar-io/ar-io-node#882]
## Summary

`ChunkMetadataAnchorSource.fetchPeerChunkHeaders` retries as `GET` after **any** non-2xx `HEAD`. For 404, 429, 402, 502 and 503 the GET returns the same answer, so the client doubles its request rate against a peer that is already refusing or failing. Combined with `validateStatus: () => true` and no backoff anywhere in the class, the client amplifies load precisely when its peer is least able to serve it.

## The code

`src/data/chunk-metadata-anchor-source.ts`

```ts
const headResponse = await this.axiosInstance.head(url, { signal, timeout: this.requestTimeoutMs });
if (headResponse.status >= 200 && headResponse.status < 300 && hasAnyChunkHeader(headResponse.headers)) {
  return headResponse.headers;
}
// ... any other status falls through ...
const getResponse = await this.axiosInstance.get(url, {
  signal, timeout: this.requestTimeoutMs,
  headers: { Range: 'bytes=0-0' }, responseType: 'arraybuffer',
});
```

The doc comment states the intent:

> Three "HEAD didn't work" cases all funnel into the same fallback:
> - HEAD threw (network error, peer down, peer doesn't support HEAD)
> - HEAD returned a non-2xx status (e.g. 405 Method Not Allowed)
> - HEAD returned 2xx but stripped the X-Arweave-Chunk-* headers

`405` is the motivating case, and the fallback is right for it. But `404` means the chunk is not there, and `429` means stop asking — neither indicates that HEAD is unsupported.

## Measured in production

turbo-gateway.com, 2026-09-03, 65,506 `/chunk/{offset}/data` requests sampled. Escalations counted as a `GET` following a `HEAD` for the same `(client IP, offset)`:

```
8,025 HEAD -> GET escalations

  3,471   HEAD 429 -> GET 429
  1,343   HEAD 402 -> GET 402
  1,077   HEAD 404 -> GET 404
    927   HEAD 429 -> GET 200
    233   HEAD 402 -> GET 429
    177   HEAD 429 -> GET 402
    148   HEAD 404 -> GET 429

75% escalate from a status where the GET cannot help.
```

During the same window the gateway saw ~12–15M chunk requests/day from ~75 distinct nodes, and a 2.7x spike (470k/hr -> 1.29M/hr) that tracked the gateway's own error rate rather than any change in client count. Rate limiting did not reduce arrival rate: two consecutive seconds from one client measured 1,971 requests (89% 429) then 2,029 requests (88% 429).

## Suggested fix

Fall through to the GET only when the outcome suggests HEAD itself is the problem:

- network/transport error (already handled)
- `405` / `501`
- 2xx with missing `X-Arweave-Chunk-*` headers (already handled)

For any other status, return `null` and let `CompositeTxBoundarySource` fall through to the chain binary search — the documented fallback. On the traffic above this removes ~6,000 of 8,025 escalations, and removes them exactly when the peer is unhealthy.

## Two related observations, not part of this fix

**The LRU cannot prevent a request.** `getTxBoundary` fetches first, parses `headerMetadata.txId`, and only then checks `this.cache.get(headerMetadata.txId)`. The cache key requires the response, so every probe is an unconditional network call. This is why single offsets are re-asked thousands of times — measured 3.6x repeat per client over 1,600 distinct offsets, and 393:1 on the busiest offsets. An offset-keyed negative cache would address it.

**`peerUrls[0]` only.** `getTxBoundary` always uses index 0 and never rotates. With the shipped default `GATEWAYS_ROOT_TX_URLS = { "https://turbo-gateway.com": 1 }`, every node's offset resolution concentrates on a single host, and nothing spreads it even when more URLs are configured.

## Environment

- `CHUNK_METADATA_ANCHOR_ENABLED` defaults to `true`
- Introduced in 8591fbc9 (#705, 2026-05-19), shipped in r79–r82
- Clients send no AR.IO headers and no custom User-Agent, so they match no header-keyed gateway rate limit

**Comment by vilenarios** [comment]
Backlog triage pass. Confirmed still valid; labelling `status.ready`.

The escalation is unchanged. `src/data/chunk-metadata-anchor-source.ts:282` gates the HEAD result on `status >= 200 && status < 300 && hasAnyChunkHeader(...)`, and anything failing that check falls through to the ranged GET at `:307`. So a 404, 429, 402, 502 or 503 all produce a second request that cannot return a different answer. With `validateStatus: () => true` at `:148`, none of those statuses is an error, so nothing backs off either.

The fix looks small and worth separating from the wider backoff question in #879: escalate to GET only where a GET could plausibly help. That is the case where HEAD succeeded but carried no usable headers, and arguably `405`/`501` where the peer does not implement HEAD at all. A refusal (`404`, `429`) or a server fault (`5xx`) should return immediately, because the second request is guaranteed to be wasted and is aimed at a peer that is already struggling.

Doing that alone removes the amplification without needing to design a backoff policy first.
